api:
    pattern:  /api.js
    defaults: { _controller: HatimeriaExtJSBundle:Direct:getApi}
route:
    pattern: /route
    defaults: { _controller: HatimeriaExtJSBundle:Direct:route}
hatimeria_login:
    pattern:  /login
    defaults: { _controller: HatimeriaExtJSBundle:Security:login }
hatimeria_after_login:
    pattern:  /after-login
    defaults: { _controller: HatimeriaExtJSBundle:Security:afterLogin }    
