api:
    pattern:  /api.js
    defaults: { _controller: HatimeriaExtJSBundle:Direct:getApi}
route:
    pattern: /route
    defaults: { _controller: HatimeriaExtJSBundle:Direct:route}
    
extjs_module_init:
    pattern: /extjs/{name}
    defaults: { _controller: HatimeriaExtJSBundle:Default:initModule}
