hatimeria_login:
    pattern:  /login
    defaults: { _controller: HatimeriaExtJSBundle:Security:login }
hatimeria_after_login:
    pattern:  /after-login
    defaults: { _controller: HatimeriaExtJSBundle:Security:afterLogin }